[book]
title = "Hábitos Atómicos"
authors = ["James Clear"]
description = "Síntesis del libro «Hábitos Atómicos» de James Clear."
language = "es"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/ivanruvalcaba/habitos-atomicos"
git-repository-icon = "fa-code-fork"
edit-url-template = "https://github.com/ivanruvalcaba/habitos-atomicos/edit/main/{path}"
